### ISSUE TITLE
missing mulled environment for FROGS Tree

### ISSUE THREAD

**Issue by mariabernard** [geraldinepascal/FROGS-wrappers#14]
@bgruening @gallardoalba, may I take a little bit more of your time to ask you a question.

We recently install FROGS 3.2.3+galaxy2 (version that you are currently improving) on our Galaxy server through the toolshed and everything went apparently good.

But for FROGS Tree, Galaxy did not generated a mulled environment with frogs, mafft, fasttree, r, r-phangorn. So each time a user launch this tool, a new conda environment is created in the job_working_directory which take a lot of time.

Do you have any idea why it'appening or how we can force Galaxy to create this mulled environment (which then need to be recognize for FROGS tree) ?

**Comment by gallardoalba** [comment]
Perhaps @mvdbeek could provide some suggestions.

**Comment by bgruening** [comment]
@mariabernard you can go to the Admin board, under Tool dependencies, search for the FROGS environment and trigger a reinstallation.

**Comment by mariabernard** [comment]
We already done that, but it still install dependancies individually whithout generating the mulled env.

**Comment by mariabernard** [comment]
I do not have access to the admin pannel currently. I will come back to you (if still available) in january.

On a local server it took more than 24 hours to generate the mulled environnment with the restricted version : 
`frogs=3.2.3 mafft=7.407 fasttree=2.1.9 r-essentials=4.0 r-phangorn=2.7.0. `
It took around 1h with relaxed versions:
frogs=3.2.3 'mafft>=7.407' 'fasttree>=2.1.9' 'r-essentials>=4.0' 'r-phangorn>=2.7.0'

but it's a problem to not kix version as results may change.... and with 19 dependancies I can not test all results with all updates!

**Comment by bgruening** [comment]
Try to dd r-base=4.1 explicitly to the requirements. R is complicated and that might help.

**Comment by mariabernard** [comment]
ok thanks
