### ISSUE TITLE
Update to FROGS 3.2

### ISSUE THREAD

**Issue by pmpcosta** [geraldinepascal/FROGS-wrappers#7]
I see that you are working in the dev branch on a 3.2 version. Is it (reasonably) functional already? Do you have a toolshed from which I could install it? Thanks in advance :)

**Comment by mariabernard** [comment]
I am still working on it. I hope that it will be accessible by the end of the month.

**Comment by mariabernard** [comment]
Hi

FOGS 3.2.2 is now available, and in particular on the toolshed : https://toolshed.g2.bx.psu.edu/view/frogs/frogs/834843ebe569
Sorry for the delay, I forgot to answer you since the publication of this new release.

Have a nice day
