### ISSUE TITLE
deprecated paths

### ISSUE THREAD

**Issue by nagoue** [geraldinepascal/FROGS-wrappers#8]
Hi,
I noticed that some paths in http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/FROGS_databases.tsv.txt are deprecated.
May you confirm for example that 
http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/SILVA/16S/silva_138.1_16S.tar.gz is now equivalent to http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/SILVA/16S/silva_138_16S.tar.gz ?
Thanks for your nice work,

**Comment by mariabernard** [comment]
Hi Nadia,

Nope! This is an error to actually upload the files!!
Thanks for your message !
