### ISSUE TITLE
frogs_data_manager repository not in https://toolshed.g2.bx.psu.edu/

### ISSUE THREAD

**Issue by loraine-gueguen** [geraldinepascal/FROGS-wrappers#9]
Hi,

I am updating/installing frogs tools and datasets on usegalaxy.fr (see https://gitlab.com/ifb-elixirfr/usegalaxy-fr/data_manager/-/merge_requests/15). 

For that, I need the frogs data manager (https://github.com/geraldinepascal/FROGS-wrappers/blob/master/FROGS_data_manager/.shed.yml), but it is unfortunately not available on the toolshed. I can see it on the testtoolshed but it is not up to date.

Could you please add this repository (frogs_data_manager) on the toolshed ?
Thanks

Regards,
Loraine

**Comment by mariabernard** [comment]
Hi Loraine,

I quickly check on the toolshed ans the frogs datamanager is included.

the repository is simply nammed frogs now on the toolshed, the last update was done the 21th of June. Here is the link to the repository:
https://toolshed.g2.bx.psu.edu/view/frogs/frogs/094a2469204d 

Did you use the same repository?

**Comment by loraine-gueguen** [comment]
I had given a wrong id for the data manager (`toolshed.g2.bx.psu.edu/repos/frogs/frogs/frogs_data_manager/3.2.2` instead of `toolshed.g2.bx.psu.edu/repos/frogs/frogs/FROGS_data_manager/3.2.2`), it is fine now :-)
Thanks!
